[package]
name = "ailmedak"
version = "0.1.0"
authors = ["aliang <aliang2344@gmail.com>"]

[dependencies]
rand = "0.3"
rust-crypto = "0.2"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "x"
path = "src/x.rs"
